# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=30)),
                ('county_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=80)),
                ('firm_address', models.CharField(max_length=80)),
                ('firm_city', models.CharField(max_length=80)),
                ('firm_zip', models.CharField(max_length=10)),
                ('firm_phone', models.CharField(max_length=11)),
                ('firm_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_name', models.CharField(max_length=30)),
                ('permit_num', models.CharField(max_length=20)),
                ('permit_type', models.CharField(max_length=40)),
                ('permit_city', models.CharField(max_length=30)),
                ('permit_state', models.CharField(max_length=14)),
                ('permit_add', models.CharField(default='ayye', max_length=80)),
                ('permit_zip', models.CharField(max_length=10)),
                ('permit_county', models.CharField(max_length=40)),
                ('permit_issue', models.CharField(max_length=12)),
                ('permit_expiration', models.CharField(max_length=12)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Firm')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_name', models.CharField(max_length=90)),
                ('pesticide_id', models.CharField(max_length=20)),
                ('pesticide_manufacturer', models.CharField(max_length=100)),
                ('pesticide_manufacturer_num', models.CharField(max_length=15)),
                ('pesticide_manufacturer_add', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grower', models.BooleanField(default=False)),
                ('is_county', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=True)),
                ('is_worker', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Firm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('rate_of_application', models.FloatField(default=0.0)),
                ('time_of_application', models.TimeField()),
                ('number_of_applications', models.IntegerField(default=0)),
                ('method_of_application', models.CharField(max_length=2)),
                ('total_application', models.IntegerField(default=0)),
                ('block_id', models.CharField(max_length=10)),
                ('status', models.CharField(default='dr', max_length=2)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to='PUR.Profile')),
                ('firm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Firm')),
                ('permit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Permit')),
                ('pesticides', models.ManyToManyField(blank=True, null=True, to='PUR.Pesticide')),
                ('reviewer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer', to='PUR.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(blank=True, max_length=30)),
                ('zone_id', models.CharField(max_length=10)),
                ('zone_section', models.CharField(max_length=10)),
                ('zone_township', models.CharField(max_length=3)),
                ('zone_township_dr', models.CharField(max_length=3)),
                ('zone_range', models.CharField(max_length=3)),
                ('zone_range_dir', models.CharField(max_length=3)),
                ('zone_bm', models.CharField(max_length=1)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Firm')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='zone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Zone'),
        ),
        migrations.AddField(
            model_name='firm',
            name='pesticides',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Pesticide'),
        ),
    ]
