# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0007_auto_20160701_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='permit_agent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_expiration',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_issue',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
