# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0008_auto_20160701_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticide',
            name='pesticide_manufacturer',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='pesticide_manufacturer_add',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='pesticide_manufacturer_num',
        ),
    ]
