# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0010_auto_20160703_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='dateEntered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
