# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0014_auto_20160706_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='zone',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Zone'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='dateUpdate',
            field=models.DateTimeField(),
        ),
    ]
