# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0020_auto_20160718_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='date_filed',
        ),
    ]
