# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0002_auto_20160628_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='zone',
        ),
        migrations.AddField(
            model_name='firm',
            name='firm_email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='report',
            name='zones',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Zone'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_zip',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to='PUR.Profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Firm'),
        ),
        migrations.AlterField(
            model_name='report',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PUR.Permit'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer', to='PUR.Profile'),
        ),
    ]
