# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0003_auto_20160630_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Profile'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_add',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firm',
        ),
        migrations.AddField(
            model_name='profile',
            name='firm',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Firm'),
        ),
    ]
