# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0005_auto_20160630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='pesticides',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Pesticide'),
        ),
    ]
