# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0006_auto_20160630_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='permit_agent',
            field=models.CharField(default='Agent', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_commodity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_county',
            field=models.CharField(default='Monterey', max_length=40),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_zip',
            field=models.CharField(max_length=11),
        ),
    ]
