# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0015_auto_20160706_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=6)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_type', models.CharField(max_length=3)),
                ('contact_permit', models.CharField(max_length=12)),
                ('contact_date', models.CharField(max_length=10)),
                ('contact_exp', models.CharField(max_length=10)),
                ('contact_address', models.CharField(max_length=80)),
                ('contact_city', models.CharField(max_length=40)),
                ('contact_state', models.CharField(max_length=2)),
                ('contact_zip', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_altPhone', models.CharField(max_length=15)),
                ('contact_fax', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='date_of_application',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creator', to='PUR.Profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUR.Firm'),
        ),
        migrations.AlterField(
            model_name='report',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUR.Permit'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reviewer', to='PUR.Profile'),
        ),
    ]
