# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUR', '0016_auto_20160711_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_permit',
            new_name='contact_permit_num',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_list',
            field=models.ManyToManyField(blank=True, null=True, to='PUR.Permit'),
        ),
    ]
